/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.14.v202310241605.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V0_COMMONAPI_EXAMPLES_HELLO_WORLD_HPP_
#define V0_COMMONAPI_EXAMPLES_HELLO_WORLD_HPP_




#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/InputStream.hpp>
#include <CommonAPI/OutputStream.hpp>
#include <CommonAPI/Types.hpp>
#include <cstdint>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v0 {
namespace commonapi {
namespace examples {

class HelloWorld {
public:
    virtual ~HelloWorld() { }

    static inline const char* getInterface();
    static inline CommonAPI::Version getInterfaceVersion();
    
    struct RoutineControlType : CommonAPI::Enumeration< uint8_t> {
        enum Literal : uint8_t {
            START = 1,
            STOP = 2,
            RESULT = 3
        };
    
        RoutineControlType()
            : CommonAPI::Enumeration< uint8_t>(static_cast< uint8_t>(Literal::START)) {}
        RoutineControlType(Literal _literal)
            : CommonAPI::Enumeration< uint8_t>(static_cast< uint8_t>(_literal)) {}
    
        inline bool validate() const {
            switch (value_) {
                case static_cast< uint8_t>(Literal::START):
                case static_cast< uint8_t>(Literal::STOP):
                case static_cast< uint8_t>(Literal::RESULT):
                return true;
            default:
                return false;
            }
        }
    
        inline bool operator==(const RoutineControlType &_other) const { return (value_ == _other.value_); }
        inline bool operator!=(const RoutineControlType &_other) const { return (value_ != _other.value_); }
        inline bool operator<=(const RoutineControlType &_other) const { return (value_ <= _other.value_); }
        inline bool operator>=(const RoutineControlType &_other) const { return (value_ >= _other.value_); }
        inline bool operator<(const RoutineControlType &_other) const { return (value_ < _other.value_); }
        inline bool operator>(const RoutineControlType &_other) const { return (value_ > _other.value_); }
    
        inline bool operator==(const Literal &_value) const { return (value_ == static_cast< uint8_t>(_value)); }
        inline bool operator!=(const Literal &_value) const { return (value_ != static_cast< uint8_t>(_value)); }
        inline bool operator<=(const Literal &_value) const { return (value_ <= static_cast< uint8_t>(_value)); }
        inline bool operator>=(const Literal &_value) const { return (value_ >= static_cast< uint8_t>(_value)); }
        inline bool operator<(const Literal &_value) const { return (value_ < static_cast< uint8_t>(_value)); }
        inline bool operator>(const Literal &_value) const { return (value_ > static_cast< uint8_t>(_value)); }
    
        const char* toString() const noexcept
        {
            switch(value_)
            {
            case static_cast< uint8_t>(Literal::START): return "START";
            case static_cast< uint8_t>(Literal::STOP): return "STOP";
            case static_cast< uint8_t>(Literal::RESULT): return "RESULT";
            default: return "UNDEFINED";
            }
        }
    };
};

const char* HelloWorld::getInterface() {
    return ("commonapi.examples.HelloWorld:v0_1");
}

CommonAPI::Version HelloWorld::getInterfaceVersion() {
    return CommonAPI::Version(0, 1);
}


} // namespace examples
} // namespace commonapi
} // namespace v0

namespace CommonAPI {
}


// Compatibility
namespace v0_1 = v0;

#endif // V0_COMMONAPI_EXAMPLES_HELLO_WORLD_HPP_
